# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
dist: xenial
cache: packages
apt_packages:
  - libv8-dev
  - ghostscript
r_binary_packages:
  - DiagrammeR
  - dplyr
  - ggplot2
  - Rcpp
  - RPostgreSQL
  - rvest
  - shiny
  - ssh
services:
  - postgresql
addons:
  postgresql: "10"
env:
  global:
  - PGPORT=5433
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
warnings_are_errors: false