# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
apt_packages:
  - libv8-dev
  - libssh-dev
  - postgresql-server-dev-10
  - ghostscript
services:
  - postgresql
addons:
  postgresql: "10"
env:
  global:
  - PGPORT=5433